frame_id: /left_lidar       #@type: string @brief: the frame id of the message
device_ip: 192.168.1.200      #@type: string @brief: the lidar ip address
msop_port: 6699               #@type: uint16_t @brief: the MSOP packets port
difop_port: 7788              #@type: uint16_t @brief: the DIFOP packets port
angle_path: /robosense/angle.csv
wait_for_difop: true
split_frame_mode: 1
cut_angle: 180                #@type: int @area 0~360
num_pkts_split: 0
start_angle: 0                #@type: int @brief: the start angle of point cloud area
end_angle: 360                #@type: int @brief: the end angle of point cloud area
min_distance: 0.2             #@type: int @brief: the minimum distance of point cloud area
max_distance: 200             #@type: int @brief: the maximum distance of point cloud area
                              #@brief: the angle to separate LiDAR scan frame
read_pcap: false              #@type: bool @brief: if ture, the lidar driver will read message from pcap bag
pcap_path: /home/xzd/项目/驱动/测试数据/32.pcap    #@type: string @brief the path of pcap bag
pcap_rate: 1
pcap_repeat: true
use_lidar_clock: false        #@type: bool @brief: if false--use system clock,if true--use lidar clock 
